# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "205862248d561114539c155a0a724055"
name = "B2Bridge"
application_url = "https://b2bridge.kaswebtechsolutions.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/delete" ]
  uri = "/webhooks/customers/delete"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_app_proxy,write_customers,write_draft_orders"

[auth]
redirect_urls = [ "https://b2bridge.kaswebtechsolutions.com/api/auth" ]

[app_proxy]
url = "https://b2bridge.kaswebtechsolutions.com/proxy"
subpath = "b2bridge-4"
prefix = "apps"
